# Generated by Django 4.2.28 on 2026-02-26 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0002_suspect_status_and_rejection'),
        ('judiciary', '0002_add_verdict_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trials', to='suspects.suspect'),
        ),
    ]
