# Generated by Django 4.2.28 on 2026-02-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('under_pursuit', 'Under Pursuit'), ('high_priority', 'High Priority'), ('arrested', 'Arrested'), ('released', 'Released'), ('convicted', 'Convicted')], default='under_pursuit', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('first_pursuit_date', models.DateTimeField(auto_now_add=True)),
                ('approved_by_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_suspects', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='cases.case')),
                ('proposed_by_detective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_suspects', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_in_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-marked_at'],
            },
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detective_probability', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('supervisor_probability', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('captain_decision', models.TextField(blank=True)),
                ('captain_decided_at', models.DateTimeField(blank=True, null=True)),
                ('chief_confirmed', models.BooleanField(default=False)),
                ('chief_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrogation_decisions', to=settings.AUTH_USER_MODEL)),
                ('chief_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrogation_chief_confirmations', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='suspects.suspect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArrestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_arrest_orders', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrest_orders', to='suspects.suspect')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='suspect',
            index=models.Index(fields=['status'], name='suspects_su_status_15e7b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='suspect',
            unique_together={('case', 'user')},
        ),
    ]
