# Generated by Django 4.2.7 on 2026-02-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='rejection_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='status',
            field=models.CharField(choices=[('under_investigation', 'Under Investigation'), ('most_wanted', 'Most Wanted'), ('arrested', 'Arrested'), ('released', 'Released'), ('convicted', 'Convicted'), ('rejected', 'Rejected')], default='under_investigation', max_length=32),
        ),
    ]
