# Generated by Django 4.2.28 on 2026-02-26 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_add_waiting_sergeant_approval'),
        ('suspects', '0002_suspect_status_and_rejection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_decision', models.CharField(choices=[('guilty', 'Guilty'), ('not_guilty', 'Not Guilty')], max_length=16)),
                ('reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_decisions', to='cases.case')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_decisions_made', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_decisions', to='suspects.suspect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChiefApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_approvals_given', to=settings.AUTH_USER_MODEL)),
                ('captain_decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chief_approval', to='suspects.captaindecision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
