# Generated by Django 4.2.28 on 2026-02-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0003_interrogation_trial_reward_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrogation',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
