# Generated by Django 4.2.28 on 2026-02-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suspects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judiciary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rials', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('gateway_pending', 'Gateway Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('gateway_reference', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_payments', to=settings.AUTH_USER_MODEL)),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine_payments', to='judiciary.trial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BailPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rials', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('supervisor_approval_needed', 'Supervisor Approval Needed'), ('approved', 'Approved'), ('gateway_pending', 'Gateway Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bail_payments', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bail_payments', to='suspects.suspect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
