# Generated by Django 4.2.28 on 2026-02-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiologicalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_results', models.TextField(blank=True)),
                ('validity_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('witness', 'Witness Statement/Media'), ('biological', 'Biological/Forensic'), ('vehicle', 'Vehicle'), ('id_document', 'ID Document'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='cases.case')),
                ('recorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Evidence',
                'ordering': ['-date_recorded', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WitnessEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(blank=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='evidence/witness/')),
                ('media_url', models.URLField(blank=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='witness_detail', to='evidence.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(blank=True, max_length=32)),
                ('serial_number', models.CharField(blank=True, max_length=64)),
                ('make_model', models.CharField(blank=True, max_length=128)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_detail', to='evidence.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='IDDocumentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.JSONField(default=dict)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_document_detail', to='evidence.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='BiologicalEvidenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence/biological/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('biological_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='evidence.biologicalevidence')),
            ],
        ),
        migrations.AddField(
            model_name='biologicalevidence',
            name='evidence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biological_detail', to='evidence.evidence'),
        ),
        migrations.AddField(
            model_name='biologicalevidence',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_biological_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_links_created', to=settings.AUTH_USER_MODEL)),
                ('evidence_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='evidence.evidence')),
                ('evidence_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='evidence.evidence')),
            ],
            options={
                'indexes': [models.Index(fields=['case'], name='evidence_ev_case_id_aa234f_idx')],
                'unique_together': {('evidence_from', 'evidence_to')},
            },
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['case', 'evidence_type'], name='evidence_ev_case_id_97293a_idx'),
        ),
    ]
