# Generated by Django 4.2.7 on 2026-02-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under Investigation'), ('waiting_sergeant_approval', 'Waiting Sergeant Approval'), ('pending_approval', 'Pending Approval'), ('referred_to_judiciary', 'Referred to Judiciary'), ('closed', 'Closed')], default='open', max_length=32),
        ),
    ]
