# Generated by Django 4.2.28 on 2026-02-26 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0003_interrogation_trial_reward_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tips_rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='suspects.suspect'),
        ),
        migrations.CreateModel(
            name='RewardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rials', models.BigIntegerField()),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_payments_made', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tips_rewards.reward')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
